OpenLake/GitStartedWithUs

- style.css
> kriti branch

- style.css
> 399_OmAnand857

- index.html
- style.css
> 	modified:   style.css

- style.css
> 104_NagaJaswanth

- style.css
I have updated my file from scratch to avoid merge conflicts.
> 181_Swarnadip

- style.css
Some commits were made without closing brackets causing bugs in style.css.
> Fixed bugs

- style.css
```
#pixel-art-container .cell:nth-child(11) {
background-color: rgb(15, 151, 172);
}
```
> updated color of th 11th cell

- style.css
> Filled colour

- style.css
Added #ff69b4 as background colour
> Added pixel for Sakshi

- style.css
sample code in css
#pixel-art-container .cell:nth-child(33) {
background-color: rgb(154, 64, 141);
}
> <cell_33> <Ayush Kumar>

- style.css
Added blue colour at the 45th cell
> <45>_<Siddhesh>

- style.css
> 284_jagathp

- style.css
assignment 1 box:229 color : rgb(51,0,255)
> from ishwar

- style.css
> Added pixel 153 - sunilkumar

- style.css
Coloured 70th pixel to steelblue
> 70_Shivangshu

- style.css
this is the first change done by me, the color of 153rd cell is changed to somewhat light blue
> cell_color_153 changed

- style.css
Added a new background color for pixel 55
> Add custom style for pixel [55]

- style.css
add gradient background to pixel 264
> Add gradient style to pixel 264

- style.css
https://github.com/OpenLake/GitStartedWithUs/issues/103
> <331>_<Chaitrali>

- style.css
added color(#6ceac2) in cell number 224
> added a cell color
